<?php
/*
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * onlyoffice/docspace-api-sdk
 *
 * A simple PHP SDK for integrating with the ONLYOFFICE DocSpace API
 *
 * The version of the OpenAPI document: 3.6.0
 * Contact: support@onlyoffice.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */


namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DocumentConfigDto Class Doc Comment
 *
 * @category Class
 * @description The document config parameters.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DocumentConfigDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DocumentConfigDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'file_type' => 'string',
        'info' => '\OpenAPI\Client\Model\InfoConfigDto',
        'is_linked_for_me' => 'bool',
        'key' => 'string',
        'permissions' => '\OpenAPI\Client\Model\PermissionsConfig',
        'shared_link_param' => 'string',
        'shared_link_key' => 'string',
        'reference_data' => '\OpenAPI\Client\Model\FileReferenceData',
        'title' => 'string',
        'url' => 'string',
        'is_form' => 'bool',
        'options' => '\OpenAPI\Client\Model\Options'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'file_type' => null,
        'info' => null,
        'is_linked_for_me' => null,
        'key' => null,
        'permissions' => null,
        'shared_link_param' => null,
        'shared_link_key' => null,
        'reference_data' => null,
        'title' => null,
        'url' => 'uri',
        'is_form' => null,
        'options' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'file_type' => true,
        'info' => false,
        'is_linked_for_me' => false,
        'key' => true,
        'permissions' => false,
        'shared_link_param' => true,
        'shared_link_key' => true,
        'reference_data' => false,
        'title' => true,
        'url' => true,
        'is_form' => false,
        'options' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'file_type' => 'fileType',
        'info' => 'info',
        'is_linked_for_me' => 'isLinkedForMe',
        'key' => 'key',
        'permissions' => 'permissions',
        'shared_link_param' => 'sharedLinkParam',
        'shared_link_key' => 'sharedLinkKey',
        'reference_data' => 'referenceData',
        'title' => 'title',
        'url' => 'url',
        'is_form' => 'isForm',
        'options' => 'options'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'file_type' => 'setFileType',
        'info' => 'setInfo',
        'is_linked_for_me' => 'setIsLinkedForMe',
        'key' => 'setKey',
        'permissions' => 'setPermissions',
        'shared_link_param' => 'setSharedLinkParam',
        'shared_link_key' => 'setSharedLinkKey',
        'reference_data' => 'setReferenceData',
        'title' => 'setTitle',
        'url' => 'setUrl',
        'is_form' => 'setIsForm',
        'options' => 'setOptions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'file_type' => 'getFileType',
        'info' => 'getInfo',
        'is_linked_for_me' => 'getIsLinkedForMe',
        'key' => 'getKey',
        'permissions' => 'getPermissions',
        'shared_link_param' => 'getSharedLinkParam',
        'shared_link_key' => 'getSharedLinkKey',
        'reference_data' => 'getReferenceData',
        'title' => 'getTitle',
        'url' => 'getUrl',
        'is_form' => 'getIsForm',
        'options' => 'getOptions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('file_type', $data ?? [], null);
        $this->setIfExists('info', $data ?? [], null);
        $this->setIfExists('is_linked_for_me', $data ?? [], null);
        $this->setIfExists('key', $data ?? [], null);
        $this->setIfExists('permissions', $data ?? [], null);
        $this->setIfExists('shared_link_param', $data ?? [], null);
        $this->setIfExists('shared_link_key', $data ?? [], null);
        $this->setIfExists('reference_data', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('is_form', $data ?? [], null);
        $this->setIfExists('options', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets file_type
     *
     * @return string|null
     */
    public function getFileType()
    {
        return $this->container['file_type'];
    }

    /**
     * Sets file_type
     *
     * @param string|null $file_type The file type of the document.
     *
     * @return self
     */
    public function setFileType($file_type)
    {
        if (is_null($file_type)) {
            array_push($this->openAPINullablesSetToNull, 'file_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('file_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['file_type'] = $file_type;

        return $this;
    }

    /**
     * Gets info
     *
     * @return \OpenAPI\Client\Model\InfoConfigDto|null
     */
    public function getInfo()
    {
        return $this->container['info'];
    }

    /**
     * Sets info
     *
     * @param \OpenAPI\Client\Model\InfoConfigDto|null $info info
     *
     * @return self
     */
    public function setInfo($info)
    {
        if (is_null($info)) {
            throw new \InvalidArgumentException('non-nullable info cannot be null');
        }
        $this->container['info'] = $info;

        return $this;
    }

    /**
     * Gets is_linked_for_me
     *
     * @return bool|null
     */
    public function getIsLinkedForMe()
    {
        return $this->container['is_linked_for_me'];
    }

    /**
     * Sets is_linked_for_me
     *
     * @param bool|null $is_linked_for_me Specifies if the documnet is linked for current user.
     *
     * @return self
     */
    public function setIsLinkedForMe($is_linked_for_me)
    {
        if (is_null($is_linked_for_me)) {
            throw new \InvalidArgumentException('non-nullable is_linked_for_me cannot be null');
        }
        $this->container['is_linked_for_me'] = $is_linked_for_me;

        return $this;
    }

    /**
     * Gets key
     *
     * @return string|null
     */
    public function getKey()
    {
        return $this->container['key'];
    }

    /**
     * Sets key
     *
     * @param string|null $key The document key.
     *
     * @return self
     */
    public function setKey($key)
    {
        if (is_null($key)) {
            array_push($this->openAPINullablesSetToNull, 'key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['key'] = $key;

        return $this;
    }

    /**
     * Gets permissions
     *
     * @return \OpenAPI\Client\Model\PermissionsConfig|null
     */
    public function getPermissions()
    {
        return $this->container['permissions'];
    }

    /**
     * Sets permissions
     *
     * @param \OpenAPI\Client\Model\PermissionsConfig|null $permissions permissions
     *
     * @return self
     */
    public function setPermissions($permissions)
    {
        if (is_null($permissions)) {
            throw new \InvalidArgumentException('non-nullable permissions cannot be null');
        }
        $this->container['permissions'] = $permissions;

        return $this;
    }

    /**
     * Gets shared_link_param
     *
     * @return string|null
     */
    public function getSharedLinkParam()
    {
        return $this->container['shared_link_param'];
    }

    /**
     * Sets shared_link_param
     *
     * @param string|null $shared_link_param The shared link parameter of the document.
     *
     * @return self
     */
    public function setSharedLinkParam($shared_link_param)
    {
        if (is_null($shared_link_param)) {
            array_push($this->openAPINullablesSetToNull, 'shared_link_param');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shared_link_param', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shared_link_param'] = $shared_link_param;

        return $this;
    }

    /**
     * Gets shared_link_key
     *
     * @return string|null
     */
    public function getSharedLinkKey()
    {
        return $this->container['shared_link_key'];
    }

    /**
     * Sets shared_link_key
     *
     * @param string|null $shared_link_key The shared link key of the document.
     *
     * @return self
     */
    public function setSharedLinkKey($shared_link_key)
    {
        if (is_null($shared_link_key)) {
            array_push($this->openAPINullablesSetToNull, 'shared_link_key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shared_link_key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shared_link_key'] = $shared_link_key;

        return $this;
    }

    /**
     * Gets reference_data
     *
     * @return \OpenAPI\Client\Model\FileReferenceData|null
     */
    public function getReferenceData()
    {
        return $this->container['reference_data'];
    }

    /**
     * Sets reference_data
     *
     * @param \OpenAPI\Client\Model\FileReferenceData|null $reference_data reference_data
     *
     * @return self
     */
    public function setReferenceData($reference_data)
    {
        if (is_null($reference_data)) {
            throw new \InvalidArgumentException('non-nullable reference_data cannot be null');
        }
        $this->container['reference_data'] = $reference_data;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title The document title.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            array_push($this->openAPINullablesSetToNull, 'title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url The document url.
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            array_push($this->openAPINullablesSetToNull, 'url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets is_form
     *
     * @return bool|null
     */
    public function getIsForm()
    {
        return $this->container['is_form'];
    }

    /**
     * Sets is_form
     *
     * @param bool|null $is_form Indicates whether this is a form.
     *
     * @return self
     */
    public function setIsForm($is_form)
    {
        if (is_null($is_form)) {
            throw new \InvalidArgumentException('non-nullable is_form cannot be null');
        }
        $this->container['is_form'] = $is_form;

        return $this;
    }

    /**
     * Gets options
     *
     * @return \OpenAPI\Client\Model\Options|null
     */
    public function getOptions()
    {
        return $this->container['options'];
    }

    /**
     * Sets options
     *
     * @param \OpenAPI\Client\Model\Options|null $options options
     *
     * @return self
     */
    public function setOptions($options)
    {
        if (is_null($options)) {
            throw new \InvalidArgumentException('non-nullable options cannot be null');
        }
        $this->container['options'] = $options;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


