<?php
/*
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * OnlyOffice/DocSpaceApiSdk
 *
 * A simple PHP SDK for integrating with the ONLYOFFICE DocSpace API
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@onlyoffice.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */


namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EmployeeDto Class Doc Comment
 *
 * @category Class
 * @description The user parameters.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EmployeeDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EmployeeDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'display_name' => 'string',
        'title' => 'string',
        'avatar' => 'string',
        'avatar_original' => 'string',
        'avatar_max' => 'string',
        'avatar_medium' => 'string',
        'avatar_small' => 'string',
        'profile_url' => 'string',
        'has_avatar' => 'bool',
        'is_anonim' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'display_name' => null,
        'title' => null,
        'avatar' => null,
        'avatar_original' => null,
        'avatar_max' => null,
        'avatar_medium' => null,
        'avatar_small' => null,
        'profile_url' => null,
        'has_avatar' => null,
        'is_anonim' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'display_name' => true,
        'title' => true,
        'avatar' => true,
        'avatar_original' => true,
        'avatar_max' => true,
        'avatar_medium' => true,
        'avatar_small' => true,
        'profile_url' => true,
        'has_avatar' => false,
        'is_anonim' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'display_name' => 'displayName',
        'title' => 'title',
        'avatar' => 'avatar',
        'avatar_original' => 'avatarOriginal',
        'avatar_max' => 'avatarMax',
        'avatar_medium' => 'avatarMedium',
        'avatar_small' => 'avatarSmall',
        'profile_url' => 'profileUrl',
        'has_avatar' => 'hasAvatar',
        'is_anonim' => 'isAnonim'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'display_name' => 'setDisplayName',
        'title' => 'setTitle',
        'avatar' => 'setAvatar',
        'avatar_original' => 'setAvatarOriginal',
        'avatar_max' => 'setAvatarMax',
        'avatar_medium' => 'setAvatarMedium',
        'avatar_small' => 'setAvatarSmall',
        'profile_url' => 'setProfileUrl',
        'has_avatar' => 'setHasAvatar',
        'is_anonim' => 'setIsAnonim'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'display_name' => 'getDisplayName',
        'title' => 'getTitle',
        'avatar' => 'getAvatar',
        'avatar_original' => 'getAvatarOriginal',
        'avatar_max' => 'getAvatarMax',
        'avatar_medium' => 'getAvatarMedium',
        'avatar_small' => 'getAvatarSmall',
        'profile_url' => 'getProfileUrl',
        'has_avatar' => 'getHasAvatar',
        'is_anonim' => 'getIsAnonim'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('display_name', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('avatar', $data ?? [], null);
        $this->setIfExists('avatar_original', $data ?? [], null);
        $this->setIfExists('avatar_max', $data ?? [], null);
        $this->setIfExists('avatar_medium', $data ?? [], null);
        $this->setIfExists('avatar_small', $data ?? [], null);
        $this->setIfExists('profile_url', $data ?? [], null);
        $this->setIfExists('has_avatar', $data ?? [], null);
        $this->setIfExists('is_anonim', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id The user ID.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string|null
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string|null $display_name The user display name.
     *
     * @return self
     */
    public function setDisplayName($display_name)
    {
        if (is_null($display_name)) {
            array_push($this->openAPINullablesSetToNull, 'display_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('display_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title The user title.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            array_push($this->openAPINullablesSetToNull, 'title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets avatar
     *
     * @return string|null
     */
    public function getAvatar()
    {
        return $this->container['avatar'];
    }

    /**
     * Sets avatar
     *
     * @param string|null $avatar The user avatar.
     *
     * @return self
     */
    public function setAvatar($avatar)
    {
        if (is_null($avatar)) {
            array_push($this->openAPINullablesSetToNull, 'avatar');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avatar', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['avatar'] = $avatar;

        return $this;
    }

    /**
     * Gets avatar_original
     *
     * @return string|null
     */
    public function getAvatarOriginal()
    {
        return $this->container['avatar_original'];
    }

    /**
     * Sets avatar_original
     *
     * @param string|null $avatar_original The user original size avatar.
     *
     * @return self
     */
    public function setAvatarOriginal($avatar_original)
    {
        if (is_null($avatar_original)) {
            array_push($this->openAPINullablesSetToNull, 'avatar_original');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avatar_original', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['avatar_original'] = $avatar_original;

        return $this;
    }

    /**
     * Gets avatar_max
     *
     * @return string|null
     */
    public function getAvatarMax()
    {
        return $this->container['avatar_max'];
    }

    /**
     * Sets avatar_max
     *
     * @param string|null $avatar_max The user maximum size avatar.
     *
     * @return self
     */
    public function setAvatarMax($avatar_max)
    {
        if (is_null($avatar_max)) {
            array_push($this->openAPINullablesSetToNull, 'avatar_max');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avatar_max', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['avatar_max'] = $avatar_max;

        return $this;
    }

    /**
     * Gets avatar_medium
     *
     * @return string|null
     */
    public function getAvatarMedium()
    {
        return $this->container['avatar_medium'];
    }

    /**
     * Sets avatar_medium
     *
     * @param string|null $avatar_medium The user medium size avatar.
     *
     * @return self
     */
    public function setAvatarMedium($avatar_medium)
    {
        if (is_null($avatar_medium)) {
            array_push($this->openAPINullablesSetToNull, 'avatar_medium');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avatar_medium', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['avatar_medium'] = $avatar_medium;

        return $this;
    }

    /**
     * Gets avatar_small
     *
     * @return string|null
     */
    public function getAvatarSmall()
    {
        return $this->container['avatar_small'];
    }

    /**
     * Sets avatar_small
     *
     * @param string|null $avatar_small The user small size avatar.
     *
     * @return self
     */
    public function setAvatarSmall($avatar_small)
    {
        if (is_null($avatar_small)) {
            array_push($this->openAPINullablesSetToNull, 'avatar_small');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avatar_small', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['avatar_small'] = $avatar_small;

        return $this;
    }

    /**
     * Gets profile_url
     *
     * @return string|null
     */
    public function getProfileUrl()
    {
        return $this->container['profile_url'];
    }

    /**
     * Sets profile_url
     *
     * @param string|null $profile_url The user profile URL.
     *
     * @return self
     */
    public function setProfileUrl($profile_url)
    {
        if (is_null($profile_url)) {
            array_push($this->openAPINullablesSetToNull, 'profile_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('profile_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['profile_url'] = $profile_url;

        return $this;
    }

    /**
     * Gets has_avatar
     *
     * @return bool|null
     */
    public function getHasAvatar()
    {
        return $this->container['has_avatar'];
    }

    /**
     * Sets has_avatar
     *
     * @param bool|null $has_avatar Specifies if the user has an avatar or not.
     *
     * @return self
     */
    public function setHasAvatar($has_avatar)
    {
        if (is_null($has_avatar)) {
            throw new \InvalidArgumentException('non-nullable has_avatar cannot be null');
        }
        $this->container['has_avatar'] = $has_avatar;

        return $this;
    }

    /**
     * Gets is_anonim
     *
     * @return bool|null
     */
    public function getIsAnonim()
    {
        return $this->container['is_anonim'];
    }

    /**
     * Sets is_anonim
     *
     * @param bool|null $is_anonim Specifies if the user is anonymous or not.
     *
     * @return self
     */
    public function setIsAnonim($is_anonim)
    {
        if (is_null($is_anonim)) {
            throw new \InvalidArgumentException('non-nullable is_anonim cannot be null');
        }
        $this->container['is_anonim'] = $is_anonim;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


