<?php
/*
 * (c) Copyright Ascensio System SIA 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * onlyoffice/docspace-api-sdk
 *
 * A simple PHP SDK for integrating with the ONLYOFFICE DocSpace API
 *
 * The version of the OpenAPI document: 3.7.0
 * Contact: support@onlyoffice.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * LoginProvider Class Doc Comment
 *
 * @category Class
 * @description [0 - Facebook, 1 - Google, 2 - Dropbox, 3 - Docusign, 4 - Box, 5 - OneDrive, 6 - GosUslugi, 7 - LinkedIn, 8 - MailRu, 9 - VK, 10 - Wordpress, 11 - Yahoo, 12 - Yandex, 13 - Github]
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LoginProvider
{
    /**
     * Possible values of this enum
     */
    public const FACEBOOK = 0;

    public const GOOGLE = 1;

    public const DROPBOX = 2;

    public const DOCUSIGN = 3;

    public const BOX = 4;

    public const ONE_DRIVE = 5;

    public const GOS_USLUGI = 6;

    public const LINKED_IN = 7;

    public const MAIL_RU = 8;

    public const VK = 9;

    public const WORDPRESS = 10;

    public const YAHOO = 11;

    public const YANDEX = 12;

    public const GITHUB = 13;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FACEBOOK,
            self::GOOGLE,
            self::DROPBOX,
            self::DOCUSIGN,
            self::BOX,
            self::ONE_DRIVE,
            self::GOS_USLUGI,
            self::LINKED_IN,
            self::MAIL_RU,
            self::VK,
            self::WORDPRESS,
            self::YAHOO,
            self::YANDEX,
            self::GITHUB
        ];
    }
}


