<?php
/*
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * OnlyOffice/DocSpaceApiSdk
 *
 * A simple PHP SDK for integrating with the ONLYOFFICE DocSpace API
 *
 * The version of the OpenAPI document: 3.6.0
 * Contact: support@onlyoffice.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */


namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PaymentSettingsDto Class Doc Comment
 *
 * @category Class
 * @description The payment settings parameters.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentSettingsDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PaymentSettingsDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sales_email' => 'string',
        'feedback_and_support_url' => 'string',
        'buy_url' => 'string',
        'standalone' => 'bool',
        'current_license' => '\OpenAPI\Client\Model\CurrentLicenseInfo',
        'max' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'sales_email' => null,
        'feedback_and_support_url' => null,
        'buy_url' => null,
        'standalone' => null,
        'current_license' => null,
        'max' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'sales_email' => true,
        'feedback_and_support_url' => true,
        'buy_url' => true,
        'standalone' => false,
        'current_license' => false,
        'max' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sales_email' => 'salesEmail',
        'feedback_and_support_url' => 'feedbackAndSupportUrl',
        'buy_url' => 'buyUrl',
        'standalone' => 'standalone',
        'current_license' => 'currentLicense',
        'max' => 'max'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sales_email' => 'setSalesEmail',
        'feedback_and_support_url' => 'setFeedbackAndSupportUrl',
        'buy_url' => 'setBuyUrl',
        'standalone' => 'setStandalone',
        'current_license' => 'setCurrentLicense',
        'max' => 'setMax'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sales_email' => 'getSalesEmail',
        'feedback_and_support_url' => 'getFeedbackAndSupportUrl',
        'buy_url' => 'getBuyUrl',
        'standalone' => 'getStandalone',
        'current_license' => 'getCurrentLicense',
        'max' => 'getMax'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('sales_email', $data ?? [], null);
        $this->setIfExists('feedback_and_support_url', $data ?? [], null);
        $this->setIfExists('buy_url', $data ?? [], null);
        $this->setIfExists('standalone', $data ?? [], null);
        $this->setIfExists('current_license', $data ?? [], null);
        $this->setIfExists('max', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['sales_email'] === null) {
            $invalidProperties[] = "'sales_email' can't be null";
        }
        if ($this->container['buy_url'] === null) {
            $invalidProperties[] = "'buy_url' can't be null";
        }
        if ($this->container['standalone'] === null) {
            $invalidProperties[] = "'standalone' can't be null";
        }
        if ($this->container['current_license'] === null) {
            $invalidProperties[] = "'current_license' can't be null";
        }
        if ($this->container['max'] === null) {
            $invalidProperties[] = "'max' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sales_email
     *
     * @return string
     */
    public function getSalesEmail()
    {
        return $this->container['sales_email'];
    }

    /**
     * Sets sales_email
     *
     * @param string $sales_email The email address for sales inquiries and support.
     *
     * @return self
     */
    public function setSalesEmail($sales_email)
    {
        if (is_null($sales_email)) {
            array_push($this->openAPINullablesSetToNull, 'sales_email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sales_email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sales_email'] = $sales_email;

        return $this;
    }

    /**
     * Gets feedback_and_support_url
     *
     * @return string|null
     */
    public function getFeedbackAndSupportUrl()
    {
        return $this->container['feedback_and_support_url'];
    }

    /**
     * Sets feedback_and_support_url
     *
     * @param string|null $feedback_and_support_url The URL for accessing the feedback and support resources.
     *
     * @return self
     */
    public function setFeedbackAndSupportUrl($feedback_and_support_url)
    {
        if (is_null($feedback_and_support_url)) {
            array_push($this->openAPINullablesSetToNull, 'feedback_and_support_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('feedback_and_support_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['feedback_and_support_url'] = $feedback_and_support_url;

        return $this;
    }

    /**
     * Gets buy_url
     *
     * @return string
     */
    public function getBuyUrl()
    {
        return $this->container['buy_url'];
    }

    /**
     * Sets buy_url
     *
     * @param string $buy_url The URL for purchasing or upgrading the product.
     *
     * @return self
     */
    public function setBuyUrl($buy_url)
    {
        if (is_null($buy_url)) {
            array_push($this->openAPINullablesSetToNull, 'buy_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('buy_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['buy_url'] = $buy_url;

        return $this;
    }

    /**
     * Gets standalone
     *
     * @return bool
     */
    public function getStandalone()
    {
        return $this->container['standalone'];
    }

    /**
     * Sets standalone
     *
     * @param bool $standalone Indicates whether the system is running in standalone mode.
     *
     * @return self
     */
    public function setStandalone($standalone)
    {
        if (is_null($standalone)) {
            throw new \InvalidArgumentException('non-nullable standalone cannot be null');
        }
        $this->container['standalone'] = $standalone;

        return $this;
    }

    /**
     * Gets current_license
     *
     * @return \OpenAPI\Client\Model\CurrentLicenseInfo
     */
    public function getCurrentLicense()
    {
        return $this->container['current_license'];
    }

    /**
     * Sets current_license
     *
     * @param \OpenAPI\Client\Model\CurrentLicenseInfo $current_license current_license
     *
     * @return self
     */
    public function setCurrentLicense($current_license)
    {
        if (is_null($current_license)) {
            throw new \InvalidArgumentException('non-nullable current_license cannot be null');
        }
        $this->container['current_license'] = $current_license;

        return $this;
    }

    /**
     * Gets max
     *
     * @return int
     */
    public function getMax()
    {
        return $this->container['max'];
    }

    /**
     * Sets max
     *
     * @param int $max The maximum quota quantity.
     *
     * @return self
     */
    public function setMax($max)
    {
        if (is_null($max)) {
            throw new \InvalidArgumentException('non-nullable max cannot be null');
        }
        $this->container['max'] = $max;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


