<?php
/*
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * OnlyOffice/DocSpaceApiSdk
 *
 * A simple PHP SDK for integrating with the ONLYOFFICE DocSpace API
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@onlyoffice.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */


namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Status Class Doc Comment
 *
 * @category Class
 * @description [0 - Ok, 1 - Invalid, 2 - Expired, 3 - Required password, 4 - Invalid password, 5 - External access denied]
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Status
{
    /**
     * Possible values of this enum
     */
    /**
     * Ok
     */
    public const OK = 0;

    /**
     * Invalid
     */
    public const INVALID = 1;

    /**
     * Expired
     */
    public const EXPIRED = 2;

    /**
     * Required password
     */
    public const REQUIRED_PASSWORD = 3;

    /**
     * Invalid password
     */
    public const INVALID_PASSWORD = 4;

    /**
     * External access denied
     */
    public const EXTERNAL_ACCESS_DENIED = 5;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OK,
            self::INVALID,
            self::EXPIRED,
            self::REQUIRED_PASSWORD,
            self::INVALID_PASSWORD,
            self::EXTERNAL_ACCESS_DENIED
        ];
    }
}


