<?php
/*
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * OnlyOffice/DocSpaceApiSdk
 *
 * A simple PHP SDK for integrating with the ONLYOFFICE DocSpace API
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@onlyoffice.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */


namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * WebhookGroupStatus Class Doc Comment
 *
 * @category Class
 * @description [0 - None, 1 - Not sent, 2 - Status2xx, 4 - Status3xx, 8 - Status4xx, 16 - Status5xx]
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookGroupStatus
{
    /**
     * Possible values of this enum
     */
    /**
     * None
     */
    public const NONE = 0;

    /**
     * Not sent
     */
    public const NOT_SENT = 1;

    /**
     * Status2xx
     */
    public const STATUS2XX = 2;

    /**
     * Status3xx
     */
    public const STATUS3XX = 4;

    /**
     * Status4xx
     */
    public const STATUS4XX = 8;

    /**
     * Status5xx
     */
    public const STATUS5XX = 16;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::NOT_SENT,
            self::STATUS2XX,
            self::STATUS3XX,
            self::STATUS4XX,
            self::STATUS5XX
        ];
    }
}


