<?php
/*
 * (c) Copyright Ascensio System SIA 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * onlyoffice/docspace-api-sdk
 *
 * A simple PHP SDK for integrating with the ONLYOFFICE DocSpace API
 *
 * The version of the OpenAPI document: 3.7.0
 * Contact: support@onlyoffice.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * WhiteLabelLogoType Class Doc Comment
 *
 * @category Class
 * @description [1 - Light small, 2 - Login page, 3 - Favicon, 4 - Docs editor, 5 - Docs editor embed, 6 - Left menu, 7 - About page, 8 - Notification, 9 - Spreadsheet editor, 10 - Spreadsheet editor embed, 11 - Presentation editor, 12 - Presentation editor embed, 13 - Pdf editor, 14 - Pdf editor embed, 15 - Diagram editor, 16 - Diagram editor embed]
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WhiteLabelLogoType
{
    /**
     * Possible values of this enum
     */
    public const LIGHT_SMALL = 1;

    public const LOGIN_PAGE = 2;

    public const FAVICON = 3;

    public const DOCS_EDITOR = 4;

    public const DOCS_EDITOR_EMBED = 5;

    public const LEFT_MENU = 6;

    public const ABOUT_PAGE = 7;

    public const NOTIFICATION = 8;

    public const SPREADSHEET_EDITOR = 9;

    public const SPREADSHEET_EDITOR_EMBED = 10;

    public const PRESENTATION_EDITOR = 11;

    public const PRESENTATION_EDITOR_EMBED = 12;

    public const PDF_EDITOR = 13;

    public const PDF_EDITOR_EMBED = 14;

    public const DIAGRAM_EDITOR = 15;

    public const DIAGRAM_EDITOR_EMBED = 16;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LIGHT_SMALL,
            self::LOGIN_PAGE,
            self::FAVICON,
            self::DOCS_EDITOR,
            self::DOCS_EDITOR_EMBED,
            self::LEFT_MENU,
            self::ABOUT_PAGE,
            self::NOTIFICATION,
            self::SPREADSHEET_EDITOR,
            self::SPREADSHEET_EDITOR_EMBED,
            self::PRESENTATION_EDITOR,
            self::PRESENTATION_EDITOR_EMBED,
            self::PDF_EDITOR,
            self::PDF_EDITOR_EMBED,
            self::DIAGRAM_EDITOR,
            self::DIAGRAM_EDITOR_EMBED
        ];
    }
}


