<?php
/*
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@onlyoffice.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */


namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 *  Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuthenticationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'authenticateMe' => [
            'application/json',
        ],
        'authenticateMeFromBodyWithCode' => [
            'application/json',
        ],
        'checkConfirm' => [
            'application/json',
        ],
        'getIsAuthentificated' => [
            'application/json',
        ],
        'logout' => [
            'application/json',
        ],
        'saveMobilePhone' => [
            'application/json',
        ],
        'sendSmsCode' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }


    /**
     * Operation authenticateMe
     *
     * Authenticate a user
     *
     * REST API Reference for authenticateMe Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authenticate-me/
     *
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authenticateMe'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\AuthenticationTokenWrapper
     */
    public function authenticateMe($auth_requests_dto = null, string $contentType = self::contentTypes['authenticateMe'][0])
    {
        list($response) = $this->authenticateMeWithHttpInfo($auth_requests_dto, $contentType);
        return $response;
    }

    /**
     * Operation authenticateMeWithHttpInfo
     *
     * Authenticate a user
     *
     * REST API Reference for authenticateMe Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authenticate-me/
     *
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authenticateMe'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\AuthenticationTokenWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function authenticateMeWithHttpInfo($auth_requests_dto = null, string $contentType = self::contentTypes['authenticateMe'][0])
    {
        $request = $this->authenticateMeRequest($auth_requests_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation authenticateMeAsync
     *
     * Authenticate a user
     *
     * REST API Reference for authenticateMe Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authenticate-me/
     *
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authenticateMe'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authenticateMeAsync($auth_requests_dto = null, string $contentType = self::contentTypes['authenticateMe'][0])
    {
        return $this->authenticateMeAsyncWithHttpInfo($auth_requests_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation authenticateMeAsyncWithHttpInfo
     *
     * Authenticate a user
     *
     * REST API Reference for authenticateMe Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authenticate-me/
     *
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authenticateMe'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authenticateMeAsyncWithHttpInfo($auth_requests_dto = null, string $contentType = self::contentTypes['authenticateMe'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AuthenticationTokenWrapper';
        $request = $this->authenticateMeRequest($auth_requests_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'authenticateMe'
     *
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authenticateMe'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function authenticateMeRequest($auth_requests_dto = null, string $contentType = self::contentTypes['authenticateMe'][0])
    {



        $resourcePath = '/api/2.0/authentication';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($auth_requests_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($auth_requests_dto));
            } else {
                $httpBody = $auth_requests_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation authenticateMeFromBodyWithCode
     *
     * Authenticate a user by code
     *
     * REST API Reference for authenticateMeFromBodyWithCode Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authenticate-me-from-body-with-code/
     *
     * @param  string $code code (required)
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authenticateMeFromBodyWithCode'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\AuthenticationTokenWrapper
     */
    public function authenticateMeFromBodyWithCode($code, $auth_requests_dto = null, string $contentType = self::contentTypes['authenticateMeFromBodyWithCode'][0])
    {
        list($response) = $this->authenticateMeFromBodyWithCodeWithHttpInfo($code, $auth_requests_dto, $contentType);
        return $response;
    }

    /**
     * Operation authenticateMeFromBodyWithCodeWithHttpInfo
     *
     * Authenticate a user by code
     *
     * REST API Reference for authenticateMeFromBodyWithCode Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authenticate-me-from-body-with-code/
     *
     * @param  string $code (required)
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authenticateMeFromBodyWithCode'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\AuthenticationTokenWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function authenticateMeFromBodyWithCodeWithHttpInfo($code, $auth_requests_dto = null, string $contentType = self::contentTypes['authenticateMeFromBodyWithCode'][0])
    {
        $request = $this->authenticateMeFromBodyWithCodeRequest($code, $auth_requests_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation authenticateMeFromBodyWithCodeAsync
     *
     * Authenticate a user by code
     *
     * REST API Reference for authenticateMeFromBodyWithCode Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authenticate-me-from-body-with-code/
     *
     * @param  string $code (required)
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authenticateMeFromBodyWithCode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authenticateMeFromBodyWithCodeAsync($code, $auth_requests_dto = null, string $contentType = self::contentTypes['authenticateMeFromBodyWithCode'][0])
    {
        return $this->authenticateMeFromBodyWithCodeAsyncWithHttpInfo($code, $auth_requests_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation authenticateMeFromBodyWithCodeAsyncWithHttpInfo
     *
     * Authenticate a user by code
     *
     * REST API Reference for authenticateMeFromBodyWithCode Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authenticate-me-from-body-with-code/
     *
     * @param  string $code (required)
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authenticateMeFromBodyWithCode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authenticateMeFromBodyWithCodeAsyncWithHttpInfo($code, $auth_requests_dto = null, string $contentType = self::contentTypes['authenticateMeFromBodyWithCode'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AuthenticationTokenWrapper';
        $request = $this->authenticateMeFromBodyWithCodeRequest($code, $auth_requests_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'authenticateMeFromBodyWithCode'
     *
     * @param  string $code (required)
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authenticateMeFromBodyWithCode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function authenticateMeFromBodyWithCodeRequest($code, $auth_requests_dto = null, string $contentType = self::contentTypes['authenticateMeFromBodyWithCode'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling authenticateMeFromBodyWithCode'
            );
        }



        $resourcePath = '/api/2.0/authentication/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($auth_requests_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($auth_requests_dto));
            } else {
                $httpBody = $auth_requests_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation checkConfirm
     *
     * Open confirmation email URL
     *
     * REST API Reference for checkConfirm Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/check-confirm/
     *
     * @param  \OpenAPI\Client\Model\EmailValidationKeyModel|null $email_validation_key_model email_validation_key_model (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkConfirm'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ConfirmWrapper
     */
    public function checkConfirm($email_validation_key_model = null, string $contentType = self::contentTypes['checkConfirm'][0])
    {
        list($response) = $this->checkConfirmWithHttpInfo($email_validation_key_model, $contentType);
        return $response;
    }

    /**
     * Operation checkConfirmWithHttpInfo
     *
     * Open confirmation email URL
     *
     * REST API Reference for checkConfirm Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/check-confirm/
     *
     * @param  \OpenAPI\Client\Model\EmailValidationKeyModel|null $email_validation_key_model (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkConfirm'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ConfirmWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function checkConfirmWithHttpInfo($email_validation_key_model = null, string $contentType = self::contentTypes['checkConfirm'][0])
    {
        $request = $this->checkConfirmRequest($email_validation_key_model, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ConfirmWrapper',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ConfirmWrapper',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ConfirmWrapper',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation checkConfirmAsync
     *
     * Open confirmation email URL
     *
     * REST API Reference for checkConfirm Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/check-confirm/
     *
     * @param  \OpenAPI\Client\Model\EmailValidationKeyModel|null $email_validation_key_model (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkConfirm'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkConfirmAsync($email_validation_key_model = null, string $contentType = self::contentTypes['checkConfirm'][0])
    {
        return $this->checkConfirmAsyncWithHttpInfo($email_validation_key_model, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation checkConfirmAsyncWithHttpInfo
     *
     * Open confirmation email URL
     *
     * REST API Reference for checkConfirm Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/check-confirm/
     *
     * @param  \OpenAPI\Client\Model\EmailValidationKeyModel|null $email_validation_key_model (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkConfirm'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function checkConfirmAsyncWithHttpInfo($email_validation_key_model = null, string $contentType = self::contentTypes['checkConfirm'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ConfirmWrapper';
        $request = $this->checkConfirmRequest($email_validation_key_model, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'checkConfirm'
     *
     * @param  \OpenAPI\Client\Model\EmailValidationKeyModel|null $email_validation_key_model (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkConfirm'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function checkConfirmRequest($email_validation_key_model = null, string $contentType = self::contentTypes['checkConfirm'][0])
    {



        $resourcePath = '/api/2.0/authentication/confirm';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($email_validation_key_model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($email_validation_key_model));
            } else {
                $httpBody = $email_validation_key_model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getIsAuthentificated
     *
     * Check authentication
     *
     * REST API Reference for getIsAuthentificated Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-is-authentificated/
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIsAuthentificated'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BooleanWrapper
     */
    public function getIsAuthentificated(string $contentType = self::contentTypes['getIsAuthentificated'][0])
    {
        list($response) = $this->getIsAuthentificatedWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getIsAuthentificatedWithHttpInfo
     *
     * Check authentication
     *
     * REST API Reference for getIsAuthentificated Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-is-authentificated/
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIsAuthentificated'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BooleanWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function getIsAuthentificatedWithHttpInfo(string $contentType = self::contentTypes['getIsAuthentificated'][0])
    {
        $request = $this->getIsAuthentificatedRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\BooleanWrapper',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\BooleanWrapper',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BooleanWrapper',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getIsAuthentificatedAsync
     *
     * Check authentication
     *
     * REST API Reference for getIsAuthentificated Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-is-authentificated/
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIsAuthentificated'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getIsAuthentificatedAsync(string $contentType = self::contentTypes['getIsAuthentificated'][0])
    {
        return $this->getIsAuthentificatedAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getIsAuthentificatedAsyncWithHttpInfo
     *
     * Check authentication
     *
     * REST API Reference for getIsAuthentificated Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/get-is-authentificated/
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIsAuthentificated'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getIsAuthentificatedAsyncWithHttpInfo(string $contentType = self::contentTypes['getIsAuthentificated'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BooleanWrapper';
        $request = $this->getIsAuthentificatedRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getIsAuthentificated'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIsAuthentificated'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getIsAuthentificatedRequest(string $contentType = self::contentTypes['getIsAuthentificated'][0])
    {


        $resourcePath = '/api/2.0/authentication';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation logout
     *
     * Log out
     *
     * REST API Reference for logout Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/logout/
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['logout'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\StringWrapper
     */
    public function logout(string $contentType = self::contentTypes['logout'][0])
    {
        list($response) = $this->logoutWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation logoutWithHttpInfo
     *
     * Log out
     *
     * REST API Reference for logout Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/logout/
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['logout'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\StringWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function logoutWithHttpInfo(string $contentType = self::contentTypes['logout'][0])
    {
        $request = $this->logoutRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\StringWrapper',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\StringWrapper',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\StringWrapper',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation logoutAsync
     *
     * Log out
     *
     * REST API Reference for logout Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/logout/
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['logout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function logoutAsync(string $contentType = self::contentTypes['logout'][0])
    {
        return $this->logoutAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation logoutAsyncWithHttpInfo
     *
     * Log out
     *
     * REST API Reference for logout Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/logout/
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['logout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function logoutAsyncWithHttpInfo(string $contentType = self::contentTypes['logout'][0])
    {
        $returnType = '\OpenAPI\Client\Model\StringWrapper';
        $request = $this->logoutRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'logout'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['logout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function logoutRequest(string $contentType = self::contentTypes['logout'][0])
    {


        $resourcePath = '/api/2.0/authentication/logout';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation saveMobilePhone
     *
     * Set a mobile phone
     *
     * REST API Reference for saveMobilePhone Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/save-mobile-phone/
     *
     * @param  \OpenAPI\Client\Model\MobileRequestsDto|null $mobile_requests_dto mobile_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['saveMobilePhone'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\AuthenticationTokenWrapper
     */
    public function saveMobilePhone($mobile_requests_dto = null, string $contentType = self::contentTypes['saveMobilePhone'][0])
    {
        list($response) = $this->saveMobilePhoneWithHttpInfo($mobile_requests_dto, $contentType);
        return $response;
    }

    /**
     * Operation saveMobilePhoneWithHttpInfo
     *
     * Set a mobile phone
     *
     * REST API Reference for saveMobilePhone Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/save-mobile-phone/
     *
     * @param  \OpenAPI\Client\Model\MobileRequestsDto|null $mobile_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['saveMobilePhone'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\AuthenticationTokenWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function saveMobilePhoneWithHttpInfo($mobile_requests_dto = null, string $contentType = self::contentTypes['saveMobilePhone'][0])
    {
        $request = $this->saveMobilePhoneRequest($mobile_requests_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation saveMobilePhoneAsync
     *
     * Set a mobile phone
     *
     * REST API Reference for saveMobilePhone Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/save-mobile-phone/
     *
     * @param  \OpenAPI\Client\Model\MobileRequestsDto|null $mobile_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['saveMobilePhone'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function saveMobilePhoneAsync($mobile_requests_dto = null, string $contentType = self::contentTypes['saveMobilePhone'][0])
    {
        return $this->saveMobilePhoneAsyncWithHttpInfo($mobile_requests_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation saveMobilePhoneAsyncWithHttpInfo
     *
     * Set a mobile phone
     *
     * REST API Reference for saveMobilePhone Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/save-mobile-phone/
     *
     * @param  \OpenAPI\Client\Model\MobileRequestsDto|null $mobile_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['saveMobilePhone'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function saveMobilePhoneAsyncWithHttpInfo($mobile_requests_dto = null, string $contentType = self::contentTypes['saveMobilePhone'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AuthenticationTokenWrapper';
        $request = $this->saveMobilePhoneRequest($mobile_requests_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'saveMobilePhone'
     *
     * @param  \OpenAPI\Client\Model\MobileRequestsDto|null $mobile_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['saveMobilePhone'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function saveMobilePhoneRequest($mobile_requests_dto = null, string $contentType = self::contentTypes['saveMobilePhone'][0])
    {



        $resourcePath = '/api/2.0/authentication/setphone';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($mobile_requests_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($mobile_requests_dto));
            } else {
                $httpBody = $mobile_requests_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('ApiKeyBearer');
        if ($apiKey !== null) {
            $headers['ApiKeyBearer'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('asc_auth_key');
        if ($apiKey !== null) {
            
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendSmsCode
     *
     * Send SMS code
     *
     * REST API Reference for sendSmsCode Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/send-sms-code/
     *
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendSmsCode'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\AuthenticationTokenWrapper
     */
    public function sendSmsCode($auth_requests_dto = null, string $contentType = self::contentTypes['sendSmsCode'][0])
    {
        list($response) = $this->sendSmsCodeWithHttpInfo($auth_requests_dto, $contentType);
        return $response;
    }

    /**
     * Operation sendSmsCodeWithHttpInfo
     *
     * Send SMS code
     *
     * REST API Reference for sendSmsCode Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/send-sms-code/
     *
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendSmsCode'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\AuthenticationTokenWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendSmsCodeWithHttpInfo($auth_requests_dto = null, string $contentType = self::contentTypes['sendSmsCode'][0])
    {
        $request = $this->sendSmsCodeRequest($auth_requests_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AuthenticationTokenWrapper',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation sendSmsCodeAsync
     *
     * Send SMS code
     *
     * REST API Reference for sendSmsCode Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/send-sms-code/
     *
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendSmsCode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendSmsCodeAsync($auth_requests_dto = null, string $contentType = self::contentTypes['sendSmsCode'][0])
    {
        return $this->sendSmsCodeAsyncWithHttpInfo($auth_requests_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendSmsCodeAsyncWithHttpInfo
     *
     * Send SMS code
     *
     * REST API Reference for sendSmsCode Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/send-sms-code/
     *
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendSmsCode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendSmsCodeAsyncWithHttpInfo($auth_requests_dto = null, string $contentType = self::contentTypes['sendSmsCode'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AuthenticationTokenWrapper';
        $request = $this->sendSmsCodeRequest($auth_requests_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendSmsCode'
     *
     * @param  \OpenAPI\Client\Model\AuthRequestsDto|null $auth_requests_dto (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendSmsCode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendSmsCodeRequest($auth_requests_dto = null, string $contentType = self::contentTypes['sendSmsCode'][0])
    {



        $resourcePath = '/api/2.0/authentication/sendsms';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($auth_requests_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($auth_requests_dto));
            } else {
                $httpBody = $auth_requests_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
