<?php
/*
 * (c) Copyright Ascensio System SIA 2025
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * onlyoffice/docspace-api-sdk
 *
 * A simple PHP SDK for integrating with the ONLYOFFICE DocSpace API
 *
 * The version of the OpenAPI document: 3.6.0
 * Contact: support@onlyoffice.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */


namespace OpenAPI\Client\Api\OAuth20;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 *  Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuthorizationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'authorizeOAuth' => [
            'application/json',
        ],
        'exchangeToken' => [
            'application/x-www-form-urlencoded',
        ],
        'submitConsent' => [
            'multipart/form-data',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }


    /**
     * Operation authorizeOAuth
     *
     * OAuth2 authorization endpoint
     *
     * REST API Reference for authorizeOAuth Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authorize-oauth/
     *
     * @param  string $response_type The OAuth 2.0 response type, must be &#39;code&#39; for authorization code flow. (required)
     * @param  string $client_id The client identifier issued to the client during registration. (required)
     * @param  string $redirect_uri The URL to redirect to after authorization is complete. (required)
     * @param  string $scope The space-separated list of requested scope permissions. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorizeOAuth'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function authorizeOAuth($response_type, $client_id, $redirect_uri, $scope, string $contentType = self::contentTypes['authorizeOAuth'][0])
    {
        $this->authorizeOAuthWithHttpInfo($response_type, $client_id, $redirect_uri, $scope, $contentType);
    }

    /**
     * Operation authorizeOAuthWithHttpInfo
     *
     * OAuth2 authorization endpoint
     *
     * REST API Reference for authorizeOAuth Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authorize-oauth/
     *
     * @param  string $response_type The OAuth 2.0 response type, must be &#39;code&#39; for authorization code flow. (required)
     * @param  string $client_id The client identifier issued to the client during registration. (required)
     * @param  string $redirect_uri The URL to redirect to after authorization is complete. (required)
     * @param  string $scope The space-separated list of requested scope permissions. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorizeOAuth'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function authorizeOAuthWithHttpInfo($response_type, $client_id, $redirect_uri, $scope, string $contentType = self::contentTypes['authorizeOAuth'][0])
    {
        $request = $this->authorizeOAuthRequest($response_type, $client_id, $redirect_uri, $scope, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation authorizeOAuthAsync
     *
     * OAuth2 authorization endpoint
     *
     * REST API Reference for authorizeOAuth Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authorize-oauth/
     *
     * @param  string $response_type The OAuth 2.0 response type, must be &#39;code&#39; for authorization code flow. (required)
     * @param  string $client_id The client identifier issued to the client during registration. (required)
     * @param  string $redirect_uri The URL to redirect to after authorization is complete. (required)
     * @param  string $scope The space-separated list of requested scope permissions. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorizeOAuth'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authorizeOAuthAsync($response_type, $client_id, $redirect_uri, $scope, string $contentType = self::contentTypes['authorizeOAuth'][0])
    {
        return $this->authorizeOAuthAsyncWithHttpInfo($response_type, $client_id, $redirect_uri, $scope, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation authorizeOAuthAsyncWithHttpInfo
     *
     * OAuth2 authorization endpoint
     *
     * REST API Reference for authorizeOAuth Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/authorize-oauth/
     *
     * @param  string $response_type The OAuth 2.0 response type, must be &#39;code&#39; for authorization code flow. (required)
     * @param  string $client_id The client identifier issued to the client during registration. (required)
     * @param  string $redirect_uri The URL to redirect to after authorization is complete. (required)
     * @param  string $scope The space-separated list of requested scope permissions. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorizeOAuth'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authorizeOAuthAsyncWithHttpInfo($response_type, $client_id, $redirect_uri, $scope, string $contentType = self::contentTypes['authorizeOAuth'][0])
    {
        $returnType = '';
        $request = $this->authorizeOAuthRequest($response_type, $client_id, $redirect_uri, $scope, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'authorizeOAuth'
     *
     * @param  string $response_type The OAuth 2.0 response type, must be &#39;code&#39; for authorization code flow. (required)
     * @param  string $client_id The client identifier issued to the client during registration. (required)
     * @param  string $redirect_uri The URL to redirect to after authorization is complete. (required)
     * @param  string $scope The space-separated list of requested scope permissions. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorizeOAuth'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function authorizeOAuthRequest($response_type, $client_id, $redirect_uri, $scope, string $contentType = self::contentTypes['authorizeOAuth'][0])
    {

        // verify the required parameter 'response_type' is set
        if ($response_type === null || (is_array($response_type) && count($response_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $response_type when calling authorizeOAuth'
            );
        }

        // verify the required parameter 'client_id' is set
        if ($client_id === null || (is_array($client_id) && count($client_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_id when calling authorizeOAuth'
            );
        }

        // verify the required parameter 'redirect_uri' is set
        if ($redirect_uri === null || (is_array($redirect_uri) && count($redirect_uri) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $redirect_uri when calling authorizeOAuth'
            );
        }

        // verify the required parameter 'scope' is set
        if ($scope === null || (is_array($scope) && count($scope) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $scope when calling authorizeOAuth'
            );
        }


        $resourcePath = '/oauth2/authorize';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $response_type,
            'response_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $client_id,
            'client_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $redirect_uri,
            'redirect_uri', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $scope,
            'scope', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('asc_auth_key');
        if ($apiKey !== null) {
            
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation exchangeToken
     *
     * OAuth2 token endpoint
     *
     * REST API Reference for exchangeToken Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/exchange-token/
     *
     * @param  string|null $grant_type The OAuth2 grant type, must be &#39;authorization_code&#39; for the authorization code flow. (optional)
     * @param  string|null $code A temporary authorization code that is sent to the client to be exchanged for a token. (optional)
     * @param  string|null $redirect_uri The URL where the user will be redirected after successful or unsuccessful authentication. (optional)
     * @param  string|null $client_id The client identifier issued to the client during registration. (optional)
     * @param  string|null $client_secret The client secret issued to the client during registration. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exchangeToken'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ExchangeToken200Response
     */
    public function exchangeToken($grant_type = null, $code = null, $redirect_uri = null, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['exchangeToken'][0])
    {
        list($response) = $this->exchangeTokenWithHttpInfo($grant_type, $code, $redirect_uri, $client_id, $client_secret, $contentType);
        return $response;
    }

    /**
     * Operation exchangeTokenWithHttpInfo
     *
     * OAuth2 token endpoint
     *
     * REST API Reference for exchangeToken Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/exchange-token/
     *
     * @param  string|null $grant_type The OAuth2 grant type, must be &#39;authorization_code&#39; for the authorization code flow. (optional)
     * @param  string|null $code A temporary authorization code that is sent to the client to be exchanged for a token. (optional)
     * @param  string|null $redirect_uri The URL where the user will be redirected after successful or unsuccessful authentication. (optional)
     * @param  string|null $client_id The client identifier issued to the client during registration. (optional)
     * @param  string|null $client_secret The client secret issued to the client during registration. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exchangeToken'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ExchangeToken200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function exchangeTokenWithHttpInfo($grant_type = null, $code = null, $redirect_uri = null, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['exchangeToken'][0])
    {
        $request = $this->exchangeTokenRequest($grant_type, $code, $redirect_uri, $client_id, $client_secret, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ExchangeToken200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ExchangeToken200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ExchangeToken200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation exchangeTokenAsync
     *
     * OAuth2 token endpoint
     *
     * REST API Reference for exchangeToken Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/exchange-token/
     *
     * @param  string|null $grant_type The OAuth2 grant type, must be &#39;authorization_code&#39; for the authorization code flow. (optional)
     * @param  string|null $code A temporary authorization code that is sent to the client to be exchanged for a token. (optional)
     * @param  string|null $redirect_uri The URL where the user will be redirected after successful or unsuccessful authentication. (optional)
     * @param  string|null $client_id The client identifier issued to the client during registration. (optional)
     * @param  string|null $client_secret The client secret issued to the client during registration. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exchangeToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function exchangeTokenAsync($grant_type = null, $code = null, $redirect_uri = null, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['exchangeToken'][0])
    {
        return $this->exchangeTokenAsyncWithHttpInfo($grant_type, $code, $redirect_uri, $client_id, $client_secret, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation exchangeTokenAsyncWithHttpInfo
     *
     * OAuth2 token endpoint
     *
     * REST API Reference for exchangeToken Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/exchange-token/
     *
     * @param  string|null $grant_type The OAuth2 grant type, must be &#39;authorization_code&#39; for the authorization code flow. (optional)
     * @param  string|null $code A temporary authorization code that is sent to the client to be exchanged for a token. (optional)
     * @param  string|null $redirect_uri The URL where the user will be redirected after successful or unsuccessful authentication. (optional)
     * @param  string|null $client_id The client identifier issued to the client during registration. (optional)
     * @param  string|null $client_secret The client secret issued to the client during registration. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exchangeToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function exchangeTokenAsyncWithHttpInfo($grant_type = null, $code = null, $redirect_uri = null, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['exchangeToken'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ExchangeToken200Response';
        $request = $this->exchangeTokenRequest($grant_type, $code, $redirect_uri, $client_id, $client_secret, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'exchangeToken'
     *
     * @param  string|null $grant_type The OAuth2 grant type, must be &#39;authorization_code&#39; for the authorization code flow. (optional)
     * @param  string|null $code A temporary authorization code that is sent to the client to be exchanged for a token. (optional)
     * @param  string|null $redirect_uri The URL where the user will be redirected after successful or unsuccessful authentication. (optional)
     * @param  string|null $client_id The client identifier issued to the client during registration. (optional)
     * @param  string|null $client_secret The client secret issued to the client during registration. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exchangeToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function exchangeTokenRequest($grant_type = null, $code = null, $redirect_uri = null, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['exchangeToken'][0])
    {







        $resourcePath = '/oauth2/token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'grant_type' => $grant_type,
            'code' => $code,
            'redirect_uri' => $redirect_uri,
            'client_id' => $client_id,
            'client_secret' => $client_secret,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation submitConsent
     *
     * OAuth2 consent endpoint
     *
     * REST API Reference for submitConsent Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/submit-consent/
     *
     * @param  string|null $client_id The client identifier issued to the client during registration. (optional)
     * @param  string|null $state The random string used to solve the CSRF vulnerability problem. (optional)
     * @param  string|null $scope The space-separated list of requested scope permissions. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitConsent'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function submitConsent($client_id = null, $state = null, $scope = null, string $contentType = self::contentTypes['submitConsent'][0])
    {
        $this->submitConsentWithHttpInfo($client_id, $state, $scope, $contentType);
    }

    /**
     * Operation submitConsentWithHttpInfo
     *
     * OAuth2 consent endpoint
     *
     * REST API Reference for submitConsent Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/submit-consent/
     *
     * @param  string|null $client_id The client identifier issued to the client during registration. (optional)
     * @param  string|null $state The random string used to solve the CSRF vulnerability problem. (optional)
     * @param  string|null $scope The space-separated list of requested scope permissions. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitConsent'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function submitConsentWithHttpInfo($client_id = null, $state = null, $scope = null, string $contentType = self::contentTypes['submitConsent'][0])
    {
        $request = $this->submitConsentRequest($client_id, $state, $scope, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation submitConsentAsync
     *
     * OAuth2 consent endpoint
     *
     * REST API Reference for submitConsent Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/submit-consent/
     *
     * @param  string|null $client_id The client identifier issued to the client during registration. (optional)
     * @param  string|null $state The random string used to solve the CSRF vulnerability problem. (optional)
     * @param  string|null $scope The space-separated list of requested scope permissions. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitConsent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitConsentAsync($client_id = null, $state = null, $scope = null, string $contentType = self::contentTypes['submitConsent'][0])
    {
        return $this->submitConsentAsyncWithHttpInfo($client_id, $state, $scope, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation submitConsentAsyncWithHttpInfo
     *
     * OAuth2 consent endpoint
     *
     * REST API Reference for submitConsent Operation
     * @see https://api.onlyoffice.com/docspace/api-backend/usage-api/submit-consent/
     *
     * @param  string|null $client_id The client identifier issued to the client during registration. (optional)
     * @param  string|null $state The random string used to solve the CSRF vulnerability problem. (optional)
     * @param  string|null $scope The space-separated list of requested scope permissions. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitConsent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitConsentAsyncWithHttpInfo($client_id = null, $state = null, $scope = null, string $contentType = self::contentTypes['submitConsent'][0])
    {
        $returnType = '';
        $request = $this->submitConsentRequest($client_id, $state, $scope, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'submitConsent'
     *
     * @param  string|null $client_id The client identifier issued to the client during registration. (optional)
     * @param  string|null $state The random string used to solve the CSRF vulnerability problem. (optional)
     * @param  string|null $scope The space-separated list of requested scope permissions. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['submitConsent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function submitConsentRequest($client_id = null, $state = null, $scope = null, string $contentType = self::contentTypes['submitConsent'][0])
    {





        $resourcePath = '/oauth2/authorize';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'client_id' => $client_id,
            'state' => $state,
            'scope' => $scope,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('asc_auth_key');
        if ($apiKey !== null) {
            
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
